// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACbI0yHrc58micNI2iYrkuVYM4YeUCgsQ',
    appId: '1:913638894218:web:14098e29a693478c44db73',
    messagingSenderId: '913638894218',
    projectId: 'food-app-crackers',
    authDomain: 'food-app-crackers.firebaseapp.com',
    storageBucket: 'food-app-crackers.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANH733ooG6pnX7sCdSoircKWdNbVBkXYY',
    appId: '1:913638894218:android:ee4ba2cb5aefedfd44db73',
    messagingSenderId: '913638894218',
    projectId: 'food-app-crackers',
    storageBucket: 'food-app-crackers.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATPKckAcPLBIfdKxnXDXSjftMtOYDN-2E',
    appId: '1:913638894218:ios:cd13b111d63a5dc744db73',
    messagingSenderId: '913638894218',
    projectId: 'food-app-crackers',
    storageBucket: 'food-app-crackers.appspot.com',
    iosClientId: '913638894218-b83sjursq8vl14jse69no9ltopknstm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATPKckAcPLBIfdKxnXDXSjftMtOYDN-2E',
    appId: '1:913638894218:ios:cd13b111d63a5dc744db73',
    messagingSenderId: '913638894218',
    projectId: 'food-app-crackers',
    storageBucket: 'food-app-crackers.appspot.com',
    iosClientId: '913638894218-b83sjursq8vl14jse69no9ltopknstm8.apps.googleusercontent.com',
    iosBundleId: 'com.example.foodApp',
  );
}
